### ISSUE TITLE
Class not found.

### ISSUE THREAD

**Issue by subashpoudel024** [vgvr0/TikTok-Video-Downloader-Python#2]
Traceback (most recent call last):
  File "d:\DATA_SCIENCE\Video-Captioning\Inefficient-works\salesforceVC\tiktok_video.py", line 1, in <module>
    from tiktok_scraper import TikTokScraper
ImportError: cannot import name 'TikTokScraper' from 'tiktok_scraper' (C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktok_scraper\__init__.py)

**Comment by MisTraleuh** [comment]
Same error

**Comment by vgvr0** [comment]
Hello! I'm sorry for the delay in answering. You can use this code, it works currently.

https://github.com/vgvr0/TikTok-Video-Downloader-using-Python-and-yt-dlp
